EQUIPMENT_SLOTS = (
    "head",
    "torso_clothing",
    "torso_armor",
    "legs_clothing",
    "legs_armor",
    "feet",
    "gloves",
    "belt",
    "belt_slot_1",
    "belt_slot_2",
    "backpack",
    "cloak",
    "ring_left",
    "ring_right",
    "main_hand",
    "off_hand",
)

HAND_SLOTS = ("main_hand", "off_hand")
BELT_ATTACHMENT_SLOTS = ("belt_slot_1", "belt_slot_2")
BELT_POUCH_SIZES = ("tiny", "small")

SLOT_LABELS = {
    "head": "Head",
    "torso_clothing": "Torso Clothing",
    "torso_armor": "Torso Armor",
    "legs_clothing": "Leg Clothing",
    "legs_armor": "Leg Armor",
    "feet": "Feet",
    "gloves": "Gloves",
    "belt": "Belt",
    "belt_slot_1": "Belt Slot 1",
    "belt_slot_2": "Belt Slot 2",
    "backpack": "Backpack",
    "cloak": "Cloak",
    "ring_left": "Left Ring",
    "ring_right": "Right Ring",
    "main_hand": "Main Hand",
    "off_hand": "Off Hand",
}

SLOT_ALIASES = {
    "helmet": "head",
    "helm": "head",
    "chest": "torso_armor",
    "torso": "torso_armor",
    "body": "torso_armor",
    "armor": "torso_armor",
    "chest_armor": "torso_armor",
    "body_armor": "torso_armor",
    "shirt": "torso_clothing",
    "clothing": "torso_clothing",
    "torso_shirt": "torso_clothing",
    "body_clothing": "torso_clothing",
    "pants": "legs_clothing",
    "trousers": "legs_clothing",
    "legs": "legs_clothing",
    "leg_armor": "legs_armor",
    "pants_armor": "legs_armor",
    "boots": "feet",
    "shoes": "feet",
    "hands": "gloves",
    "glove": "gloves",
    "belt_slot": "belt_slot_1",
    "belt_slot_one": "belt_slot_1",
    "belt_slot_two": "belt_slot_2",
    "belt_1": "belt_slot_1",
    "belt_2": "belt_slot_2",
    "belt_left": "belt_slot_1",
    "belt_right": "belt_slot_2",
    "weapon_belt": "belt_slot_1",
    "pouch_belt": "belt_slot_1",
    "ring": "ring_left",
    "left_ring": "ring_left",
    "right_ring": "ring_right",
    "back": "backpack",
    "bag": "backpack",
    "rucksack": "backpack",
    "main": "main_hand",
    "right_hand": "main_hand",
    "weapon_hand": "main_hand",
    "off": "off_hand",
    "left_hand": "off_hand",
}
