MAX_SKILL_LEVEL = 100
SKILL_XP_BASE_COST = 100
SKILL_XP_CURVE_EXPONENT = 1.55
MAX_CUSTOM_SKILLS_PER_CHARACTER = 20

LEGACY_CORE_SKILL_ALIASES = {
    "Schwertkampf": "Swordsmanship",
    "Axt & Hammer": "Axes & Hammers",
    "Stangenwaffen": "Polearms",
    "Bogenschießen": "Archery",
    "Ausweichen": "Dodging",
    "Blocken": "Blocking",
    "Schleichen": "Stealth",
    "Schlösser knacken": "Lockpicking",
    "Taschendiebstahl": "Pickpocketing",
    "Fallen entschärfen": "Trap Disarming",
    "Klettern": "Climbing",
    "Arkanes Wissen": "Arcane Lore",
    "Kräuterkunde": "Herbalism",
    "Heilkunde": "Medicine",
    "Überleben": "Survival",
    "Überzeugen": "Persuasion",
    "Täuschen": "Deception",
    "Einschüchtern": "Intimidation",
    "Menschenkenntnis": "Insight",
}

CORE_SKILLS = [
    {
        "name": "Swordsmanship",
        "category": "Combat",
        "linked_attribute": "strength",
        "secondary_attributes": ["dexterity"],
        "icon": "⚔️",
        "short_code": "SWD",
        "description": "Training with swords and balanced bladed melee weapons.",
    },
    {
        "name": "Axes & Hammers",
        "category": "Combat",
        "linked_attribute": "strength",
        "secondary_attributes": ["constitution"],
        "icon": "🪓",
        "short_code": "AXE",
        "description": "Heavy melee weapon handling for axes, hammers and crushing force.",
    },
    {
        "name": "Polearms",
        "category": "Combat",
        "linked_attribute": "strength",
        "secondary_attributes": ["dexterity"],
        "icon": "🔱",
        "short_code": "POL",
        "description": "Spears, polearms and reach-based melee combat.",
    },
    {
        "name": "Archery",
        "category": "Combat",
        "linked_attribute": "dexterity",
        "secondary_attributes": ["perception"],
        "icon": "🏹",
        "short_code": "BOW",
        "description": "Ranged combat with bows and careful aim.",
    },
    {
        "name": "Dodging",
        "category": "Combat",
        "linked_attribute": "dexterity",
        "secondary_attributes": ["perception"],
        "icon": "💨",
        "short_code": "DOD",
        "description": "Dodging, evasive movement and avoiding incoming danger.",
    },
    {
        "name": "Blocking",
        "category": "Combat",
        "linked_attribute": "constitution",
        "secondary_attributes": ["strength"],
        "icon": "🛡️",
        "short_code": "BLK",
        "description": "Blocking, bracing and absorbing attacks with shields or guard positions.",
    },
    {
        "name": "Stealth",
        "category": "Utility",
        "linked_attribute": "dexterity",
        "secondary_attributes": ["perception"],
        "icon": "👣",
        "short_code": "SNK",
        "description": "Moving quietly, hiding and avoiding attention.",
    },
    {
        "name": "Lockpicking",
        "category": "Utility",
        "linked_attribute": "dexterity",
        "secondary_attributes": ["intelligence"],
        "icon": "🗝️",
        "short_code": "LOK",
        "description": "Opening locks through tools, touch and mechanical understanding.",
    },
    {
        "name": "Pickpocketing",
        "category": "Utility",
        "linked_attribute": "dexterity",
        "secondary_attributes": ["perception"],
        "icon": "✋",
        "short_code": "PCK",
        "description": "Stealing small items unnoticed through timing and nimble hands.",
    },
    {
        "name": "Trap Disarming",
        "category": "Utility",
        "linked_attribute": "intelligence",
        "secondary_attributes": ["dexterity", "perception"],
        "icon": "🪤",
        "short_code": "TRP",
        "description": "Spotting, understanding and disabling traps.",
    },
    {
        "name": "Climbing",
        "category": "Utility",
        "linked_attribute": "strength",
        "secondary_attributes": ["dexterity"],
        "icon": "🧗",
        "short_code": "CLM",
        "description": "Climbing walls, cliffs, ropes and difficult vertical terrain.",
    },
    {
        "name": "Athletics",
        "category": "Utility",
        "linked_attribute": "strength",
        "secondary_attributes": ["constitution", "dexterity"],
        "icon": "🏃",
        "short_code": "ATH",
        "description": "Running, jumping, swimming and sustained physical effort.",
    },
    {
        "name": "Arcane Lore",
        "category": "Knowledge",
        "linked_attribute": "intelligence",
        "secondary_attributes": [],
        "icon": "✨",
        "short_code": "ARC",
        "description": "Knowledge of magic, runes, rituals and supernatural artifacts.",
    },
    {
        "name": "Herbalism",
        "category": "Knowledge",
        "linked_attribute": "intelligence",
        "secondary_attributes": ["perception"],
        "icon": "🌿",
        "short_code": "HER",
        "description": "Identifying herbs, natural remedies, toxins and useful plants.",
    },
    {
        "name": "Medicine",
        "category": "Knowledge",
        "linked_attribute": "intelligence",
        "secondary_attributes": ["perception"],
        "icon": "🩹",
        "short_code": "MED",
        "description": "Treating wounds, recognizing illness and stabilizing the injured.",
    },
    {
        "name": "Survival",
        "category": "Knowledge",
        "linked_attribute": "perception",
        "secondary_attributes": ["constitution"],
        "icon": "🏕️",
        "short_code": "SUR",
        "description": "Wilderness survival, campcraft, weather sense, food and tracks.",
    },
    {
        "name": "Persuasion",
        "category": "Social",
        "linked_attribute": "charisma",
        "secondary_attributes": ["intelligence"],
        "icon": "🤝",
        "short_code": "PRS",
        "description": "Diplomacy, honest argument and winning someone over.",
    },
    {
        "name": "Deception",
        "category": "Social",
        "linked_attribute": "charisma",
        "secondary_attributes": ["intelligence"],
        "icon": "🎭",
        "short_code": "DEC",
        "description": "Lying, disguises, misdirection and false identities.",
    },
    {
        "name": "Intimidation",
        "category": "Social",
        "linked_attribute": "charisma",
        "secondary_attributes": ["strength"],
        "icon": "😠",
        "short_code": "ITM",
        "description": "Threats, dominance and making others back down.",
    },
    {
        "name": "Insight",
        "category": "Social",
        "linked_attribute": "perception",
        "secondary_attributes": ["charisma"],
        "icon": "🧐",
        "short_code": "INS",
        "description": "Reading motives, sensing lies and understanding social cues.",
    },
]
