"""Enemy archetype presets and class-based generation helpers.

This module keeps broad class presets for animals, humanoids, and fantasy foes
so we can generate many consistent enemies without hand-authoring each one.
"""

from __future__ import annotations

from copy import deepcopy


ENEMY_ARCHETYPES = {
    # Small prey / vermin
    "rat_small": {
        "category": "animal",
        "level_min": 1,
        "level_max": 1,
        "hp_base": 5,
        "hp_per_level": 0,
        "attack_base": 10,
        "attack_per_level": 0.8,
        "dodge_base": 12,
        "dodge_per_level": 0.7,
        "block_base": 2,
        "block_per_level": 0.2,
        "damage_base_min": 1,
        "damage_base_max": 3,
        "damage_per_level": 0.2,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Rat Meat", "item_type": "consumable", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "small_prey": {
        "category": "animal",
        "level_min": 1,
        "level_max": 4,
        "hp_base": 6,
        "hp_per_level": 2,
        "attack_base": 12,
        "attack_per_level": 1.2,
        "dodge_base": 14,
        "dodge_per_level": 0.8,
        "block_base": 3,
        "block_per_level": 0.2,
        "damage_base_min": 2,
        "damage_base_max": 4,
        "damage_per_level": 0.35,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Small Game Meat", "item_type": "consumable", "size": "tiny", "weight": 0.2, "volume": 0.2}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "cellar_rat": {
        "category": "animal",
        "level_min": 1,
        "level_max": 2,
        "hp_base": 7,
        "hp_per_level": 2,
        "attack_base": 11,
        "attack_per_level": 1.0,
        "dodge_base": 13,
        "dodge_per_level": 0.8,
        "block_base": 2,
        "block_per_level": 0.2,
        "damage_base_min": 1,
        "damage_base_max": 4,
        "damage_per_level": 0.2,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Rat Tail", "item_type": "material", "size": "tiny", "weight": 0.05, "volume": 0.05}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "bat_swarm": {
        "category": "animal",
        "level_min": 2,
        "level_max": 5,
        "hp_base": 12,
        "hp_per_level": 5,
        "attack_base": 13,
        "attack_per_level": 1.0,
        "dodge_base": 18,
        "dodge_per_level": 1.1,
        "block_base": 2,
        "block_per_level": 0.2,
        "damage_base_min": 2,
        "damage_base_max": 5,
        "damage_per_level": 0.3,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Bat Wing", "item_type": "material", "size": "tiny", "weight": 0.05, "volume": 0.05}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "spider_swarm_small": {
        "category": "animal",
        "level_min": 2,
        "level_max": 5,
        "hp_base": 10,
        "hp_per_level": 4,
        "attack_base": 14,
        "attack_per_level": 1.1,
        "dodge_base": 16,
        "dodge_per_level": 1.0,
        "block_base": 3,
        "block_per_level": 0.2,
        "damage_base_min": 2,
        "damage_base_max": 6,
        "damage_per_level": 0.35,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Spider Silk", "item_type": "material", "size": "tiny", "weight": 0.05, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "venom_snake_small": {
        "category": "animal",
        "level_min": 3,
        "level_max": 5,
        "hp_base": 16,
        "hp_per_level": 6,
        "attack_base": 16,
        "attack_per_level": 1.2,
        "dodge_base": 17,
        "dodge_per_level": 0.9,
        "block_base": 4,
        "block_per_level": 0.3,
        "damage_base_min": 3,
        "damage_base_max": 7,
        "damage_per_level": 0.45,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Snake Venom Sac", "item_type": "material", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "slime_tiny": {
        "category": "monster",
        "level_min": 1,
        "level_max": 3,
        "hp_base": 14,
        "hp_per_level": 6,
        "attack_base": 10,
        "attack_per_level": 0.9,
        "dodge_base": 8,
        "dodge_per_level": 0.4,
        "block_base": 9,
        "block_per_level": 0.5,
        "damage_base_min": 2,
        "damage_base_max": 5,
        "damage_per_level": 0.35,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Slime Gel", "item_type": "material", "size": "tiny", "weight": 0.3, "volume": 0.3}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "slime_common": {
        "category": "monster",
        "level_min": 4,
        "level_max": 7,
        "hp_base": 44,
        "hp_per_level": 10,
        "attack_base": 16,
        "attack_per_level": 1.2,
        "dodge_base": 10,
        "dodge_per_level": 0.5,
        "block_base": 12,
        "block_per_level": 0.6,
        "damage_base_min": 5,
        "damage_base_max": 10,
        "damage_per_level": 0.65,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Dense Slime Gel", "item_type": "material", "size": "small", "weight": 0.7, "volume": 0.6}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "slime_acid": {
        "category": "monster",
        "level_min": 8,
        "level_max": 12,
        "hp_base": 92,
        "hp_per_level": 14,
        "attack_base": 24,
        "attack_per_level": 1.6,
        "dodge_base": 11,
        "dodge_per_level": 0.5,
        "block_base": 16,
        "block_per_level": 0.8,
        "damage_base_min": 10,
        "damage_base_max": 18,
        "damage_per_level": 0.95,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Acidic Slime Core", "item_type": "material", "size": "small", "weight": 0.8, "volume": 0.6}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "slime_elder": {
        "category": "monster",
        "level_min": 13,
        "level_max": 20,
        "hp_base": 180,
        "hp_per_level": 22,
        "attack_base": 34,
        "attack_per_level": 2.0,
        "dodge_base": 12,
        "dodge_per_level": 0.6,
        "block_base": 24,
        "block_per_level": 1.1,
        "damage_base_min": 16,
        "damage_base_max": 28,
        "damage_per_level": 1.3,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Elder Slime Residue", "item_type": "material", "size": "small", "weight": 1.0, "volume": 0.8}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "wolf_scout": {
        "category": "animal",
        "level_min": 5,
        "level_max": 7,
        "hp_base": 48,
        "hp_per_level": 10,
        "attack_base": 24,
        "attack_per_level": 1.7,
        "dodge_base": 18,
        "dodge_per_level": 0.9,
        "block_base": 8,
        "block_per_level": 0.5,
        "damage_base_min": 8,
        "damage_base_max": 14,
        "damage_per_level": 0.8,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Wolf Pelt", "item_type": "material", "size": "small", "weight": 1.0, "volume": 1.0}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "wolf_pack_hunter": {
        "category": "animal",
        "level_min": 7,
        "level_max": 10,
        "hp_base": 72,
        "hp_per_level": 12,
        "attack_base": 28,
        "attack_per_level": 1.8,
        "dodge_base": 19,
        "dodge_per_level": 1.0,
        "block_base": 9,
        "block_per_level": 0.6,
        "damage_base_min": 10,
        "damage_base_max": 17,
        "damage_per_level": 1.0,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Prime Wolf Pelt", "item_type": "material", "size": "small", "weight": 1.2, "volume": 1.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "wild_boar": {
        "category": "animal",
        "level_min": 5,
        "level_max": 8,
        "hp_base": 82,
        "hp_per_level": 14,
        "attack_base": 26,
        "attack_per_level": 1.8,
        "dodge_base": 14,
        "dodge_per_level": 0.6,
        "block_base": 13,
        "block_per_level": 0.9,
        "damage_base_min": 10,
        "damage_base_max": 18,
        "damage_per_level": 1.0,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Boar Meat", "item_type": "consumable", "size": "small", "weight": 1.2, "volume": 1.0}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "boar_alpha": {
        "category": "animal",
        "level_min": 8,
        "level_max": 10,
        "hp_base": 140,
        "hp_per_level": 18,
        "attack_base": 31,
        "attack_per_level": 2.0,
        "dodge_base": 15,
        "dodge_per_level": 0.7,
        "block_base": 16,
        "block_per_level": 1.0,
        "damage_base_min": 13,
        "damage_base_max": 22,
        "damage_per_level": 1.2,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Alpha Boar Tusk", "item_type": "material", "size": "small", "weight": 0.8, "volume": 0.5}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "venom_snake_large": {
        "category": "animal",
        "level_min": 6,
        "level_max": 10,
        "hp_base": 44,
        "hp_per_level": 9,
        "attack_base": 24,
        "attack_per_level": 1.5,
        "dodge_base": 19,
        "dodge_per_level": 1.0,
        "block_base": 7,
        "block_per_level": 0.4,
        "damage_base_min": 8,
        "damage_base_max": 15,
        "damage_per_level": 0.9,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Venom Gland", "item_type": "material", "size": "tiny", "weight": 0.2, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "giant_spider_small": {
        "category": "animal",
        "level_min": 7,
        "level_max": 10,
        "hp_base": 60,
        "hp_per_level": 11,
        "attack_base": 25,
        "attack_per_level": 1.6,
        "dodge_base": 17,
        "dodge_per_level": 0.9,
        "block_base": 10,
        "block_per_level": 0.6,
        "damage_base_min": 9,
        "damage_base_max": 16,
        "damage_per_level": 1.0,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Thick Spider Silk", "item_type": "material", "size": "small", "weight": 0.4, "volume": 0.3}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "reef_shark_small": {
        "category": "animal",
        "level_min": 8,
        "level_max": 10,
        "hp_base": 110,
        "hp_per_level": 16,
        "attack_base": 30,
        "attack_per_level": 1.9,
        "dodge_base": 16,
        "dodge_per_level": 0.7,
        "block_base": 12,
        "block_per_level": 0.8,
        "damage_base_min": 12,
        "damage_base_max": 20,
        "damage_per_level": 1.1,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Shark Tooth", "item_type": "material", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "restless_spirit_minor": {
        "category": "undead",
        "level_min": 5,
        "level_max": 8,
        "hp_base": 52,
        "hp_per_level": 9,
        "attack_base": 22,
        "attack_per_level": 1.4,
        "dodge_base": 20,
        "dodge_per_level": 1.0,
        "block_base": 8,
        "block_per_level": 0.4,
        "damage_base_min": 7,
        "damage_base_max": 14,
        "damage_per_level": 0.9,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Ectoplasm Residue", "item_type": "material", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": False,
        "allows_ceasefire": False,
    },
    "grave_walker": {
        "category": "undead",
        "level_min": 6,
        "level_max": 9,
        "hp_base": 86,
        "hp_per_level": 12,
        "attack_base": 24,
        "attack_per_level": 1.5,
        "dodge_base": 12,
        "dodge_per_level": 0.6,
        "block_base": 14,
        "block_per_level": 0.8,
        "damage_base_min": 9,
        "damage_base_max": 16,
        "damage_per_level": 1.0,
        "equipment": [{"name": "Rusty Graveblade", "item_type": "weapon", "size": "medium", "weight": 2.0, "volume": 1.5, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 6}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Bone Fragment", "item_type": "material", "size": "tiny", "weight": 0.2, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": False,
        "allows_ceasefire": False,
    },
    "street_thug_novice": {
        "category": "humanoid",
        "level_min": 3,
        "level_max": 5,
        "hp_base": 42,
        "hp_per_level": 8,
        "attack_base": 16,
        "attack_per_level": 1.1,
        "dodge_base": 12,
        "dodge_per_level": 0.6,
        "block_base": 11,
        "block_per_level": 0.6,
        "damage_base_min": 5,
        "damage_base_max": 10,
        "damage_per_level": 0.5,
        "equipment": [{"name": "Crude Club", "item_type": "weapon", "size": "medium", "weight": 2.2, "volume": 1.8, "hand_usage": "one_handed", "weapon_family": "mace_club", "item_level": 4}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 15},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "pickpocket": {
        "category": "humanoid",
        "level_min": 2,
        "level_max": 5,
        "hp_base": 34,
        "hp_per_level": 7,
        "attack_base": 14,
        "attack_per_level": 1.0,
        "dodge_base": 16,
        "dodge_per_level": 1.0,
        "block_base": 8,
        "block_per_level": 0.4,
        "damage_base_min": 4,
        "damage_base_max": 8,
        "damage_per_level": 0.45,
        "equipment": [{"name": "Pickpocket Dagger", "item_type": "weapon", "size": "small", "weight": 0.7, "volume": 0.5, "hand_usage": "one_handed", "weapon_family": "dagger", "item_level": 4}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 22},
        "loot_items": [{"name": "Stolen Trinket", "item_type": "misc", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "bandit_cutpurse": {
        "category": "humanoid",
        "level_min": 5,
        "level_max": 7,
        "hp_base": 64,
        "hp_per_level": 10,
        "attack_base": 22,
        "attack_per_level": 1.4,
        "dodge_base": 16,
        "dodge_per_level": 0.8,
        "block_base": 12,
        "block_per_level": 0.6,
        "damage_base_min": 8,
        "damage_base_max": 14,
        "damage_per_level": 0.8,
        "equipment": [{"name": "Cutpurse Knife", "item_type": "weapon", "size": "small", "weight": 0.8, "volume": 0.6, "hand_usage": "one_handed", "weapon_family": "dagger", "item_level": 6}],
        "loot_currency": {"gold": 0, "silver": 1, "copper": 30},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "bandit_raider": {
        "category": "humanoid",
        "level_min": 7,
        "level_max": 10,
        "hp_base": 94,
        "hp_per_level": 12,
        "attack_base": 28,
        "attack_per_level": 1.6,
        "dodge_base": 17,
        "dodge_per_level": 0.8,
        "block_base": 15,
        "block_per_level": 0.8,
        "damage_base_min": 11,
        "damage_base_max": 19,
        "damage_per_level": 1.0,
        "equipment": [
            {"name": "Raider Hatchet", "item_type": "weapon", "size": "medium", "weight": 1.8, "volume": 1.3, "hand_usage": "one_handed", "weapon_family": "axe_hammer", "item_level": 9},
            {"name": "Raider Leather", "item_type": "armor", "size": "small", "weight": 2.5, "volume": 1.8, "armor_class": "light", "armor_rating": 10},
        ],
        "loot_currency": {"gold": 0, "silver": 2, "copper": 45},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "deserter_soldier": {
        "category": "humanoid",
        "level_min": 7,
        "level_max": 10,
        "hp_base": 110,
        "hp_per_level": 14,
        "attack_base": 30,
        "attack_per_level": 1.7,
        "dodge_base": 16,
        "dodge_per_level": 0.7,
        "block_base": 18,
        "block_per_level": 0.9,
        "damage_base_min": 12,
        "damage_base_max": 20,
        "damage_per_level": 1.1,
        "equipment": [
            {"name": "Deserter Sword", "item_type": "weapon", "size": "medium", "weight": 2.3, "volume": 1.6, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 10},
            {"name": "Deserter Shield", "item_type": "shield", "size": "medium", "weight": 3.8, "volume": 2.0, "armor_rating": 10, "block_bonus": 5, "block_threshold_bonus": 2},
        ],
        "loot_currency": {"gold": 0, "silver": 2, "copper": 35},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "goblin_skirmisher": {
        "category": "humanoid",
        "level_min": 5,
        "level_max": 8,
        "hp_base": 58,
        "hp_per_level": 9,
        "attack_base": 21,
        "attack_per_level": 1.3,
        "dodge_base": 18,
        "dodge_per_level": 0.9,
        "block_base": 9,
        "block_per_level": 0.5,
        "damage_base_min": 7,
        "damage_base_max": 13,
        "damage_per_level": 0.75,
        "equipment": [{"name": "Goblin Shiv", "item_type": "weapon", "size": "small", "weight": 0.7, "volume": 0.5, "hand_usage": "one_handed", "weapon_family": "dagger", "item_level": 6}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 18},
        "loot_items": [{"name": "Goblin Ear", "item_type": "quest", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "orc_scout": {
        "category": "humanoid",
        "level_min": 7,
        "level_max": 10,
        "hp_base": 102,
        "hp_per_level": 13,
        "attack_base": 32,
        "attack_per_level": 1.9,
        "dodge_base": 14,
        "dodge_per_level": 0.7,
        "block_base": 16,
        "block_per_level": 0.8,
        "damage_base_min": 12,
        "damage_base_max": 21,
        "damage_per_level": 1.1,
        "equipment": [{"name": "Orc Chopper", "item_type": "weapon", "size": "medium", "weight": 2.4, "volume": 1.8, "hand_usage": "one_handed", "weapon_family": "axe_hammer", "item_level": 9}],
        "loot_currency": {"gold": 0, "silver": 1, "copper": 22},
        "loot_items": [],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "predator_medium": {
        "category": "animal",
        "level_min": 5,
        "level_max": 12,
        "hp_base": 45,
        "hp_per_level": 12,
        "attack_base": 22,
        "attack_per_level": 1.8,
        "dodge_base": 18,
        "dodge_per_level": 0.9,
        "block_base": 8,
        "block_per_level": 0.4,
        "damage_base_min": 7,
        "damage_base_max": 14,
        "damage_per_level": 0.9,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Predator Pelt", "item_type": "material", "size": "small", "weight": 1.0, "volume": 1.0}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "brute_beast": {
        "category": "animal",
        "level_min": 10,
        "level_max": 20,
        "hp_base": 140,
        "hp_per_level": 26,
        "attack_base": 30,
        "attack_per_level": 2.1,
        "dodge_base": 14,
        "dodge_per_level": 0.6,
        "block_base": 15,
        "block_per_level": 0.9,
        "damage_base_min": 14,
        "damage_base_max": 24,
        "damage_per_level": 1.4,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Thick Hide", "item_type": "material", "size": "medium", "weight": 3.0, "volume": 2.0}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "aquatic_predator": {
        "category": "animal",
        "level_min": 10,
        "level_max": 22,
        "hp_base": 120,
        "hp_per_level": 24,
        "attack_base": 32,
        "attack_per_level": 2.0,
        "dodge_base": 16,
        "dodge_per_level": 0.7,
        "block_base": 14,
        "block_per_level": 0.8,
        "damage_base_min": 13,
        "damage_base_max": 23,
        "damage_per_level": 1.3,
        "equipment": [],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 0},
        "loot_items": [{"name": "Beast Meat", "item_type": "material", "size": "medium", "weight": 2.5, "volume": 2.0}],
        "allows_surrender": False,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    # Humanoids
    "civilian_weak": {
        "category": "humanoid",
        "level_min": 1,
        "level_max": 3,
        "hp_base": 22,
        "hp_per_level": 4,
        "attack_base": 9,
        "attack_per_level": 0.6,
        "dodge_base": 8,
        "dodge_per_level": 0.5,
        "block_base": 6,
        "block_per_level": 0.5,
        "damage_base_min": 2,
        "damage_base_max": 5,
        "damage_per_level": 0.3,
        "equipment": [{"name": "Worn Clothes", "item_type": "clothing", "size": "small", "weight": 0.7, "volume": 0.8}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 3},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "civilian_worker": {
        "category": "humanoid",
        "level_min": 3,
        "level_max": 10,
        "hp_base": 35,
        "hp_per_level": 7,
        "attack_base": 14,
        "attack_per_level": 0.9,
        "dodge_base": 11,
        "dodge_per_level": 0.6,
        "block_base": 10,
        "block_per_level": 0.6,
        "damage_base_min": 4,
        "damage_base_max": 8,
        "damage_per_level": 0.45,
        "equipment": [{"name": "Work Apron", "item_type": "clothing", "size": "small", "weight": 0.8, "volume": 0.8}],
        "loot_currency": {"gold": 0, "silver": 0, "copper": 8},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "thug_bandit": {
        "category": "humanoid",
        "level_min": 5,
        "level_max": 15,
        "hp_base": 70,
        "hp_per_level": 12,
        "attack_base": 24,
        "attack_per_level": 1.5,
        "dodge_base": 16,
        "dodge_per_level": 0.8,
        "block_base": 14,
        "block_per_level": 0.7,
        "damage_base_min": 8,
        "damage_base_max": 16,
        "damage_per_level": 0.9,
        "equipment": [
            {"name": "Bandit Blade", "item_type": "weapon", "size": "medium", "weight": 1.8, "volume": 1.4, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 8},
            {"name": "Padded Jerkin", "item_type": "armor", "size": "small", "weight": 2.0, "volume": 1.6, "armor_class": "light", "armor_rating": 8},
        ],
        "loot_currency": {"gold": 0, "silver": 1, "copper": 25},
        "loot_items": [{"name": "Crude Lockpick", "item_type": "tool", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": False,
    },
    "guard_standard": {
        "category": "humanoid",
        "level_min": 25,
        "level_max": 25,
        "hp_base": 330,
        "hp_per_level": 0,
        "attack_base": 56,
        "attack_per_level": 0,
        "dodge_base": 34,
        "dodge_per_level": 0,
        "block_base": 52,
        "block_per_level": 0,
        "damage_base_min": 42,
        "damage_base_max": 70,
        "damage_per_level": 0,
        "equipment": [
            {"name": "Guard Sword", "item_type": "weapon", "size": "medium", "weight": 2.6, "volume": 1.8, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 25},
            {"name": "Guard Shield", "item_type": "shield", "size": "medium", "weight": 4.2, "volume": 2.2, "armor_rating": 14, "block_bonus": 8, "block_threshold_bonus": 3},
            {"name": "Guard Mail", "item_type": "armor", "size": "medium", "weight": 8.5, "volume": 3.0, "armor_class": "medium", "armor_rating": 22},
        ],
        "loot_currency": {"gold": 0, "silver": 5, "copper": 45},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "guard_captain": {
        "category": "humanoid",
        "level_min": 35,
        "level_max": 35,
        "hp_base": 680,
        "hp_per_level": 0,
        "attack_base": 78,
        "attack_per_level": 0,
        "dodge_base": 44,
        "dodge_per_level": 0,
        "block_base": 72,
        "block_per_level": 0,
        "damage_base_min": 70,
        "damage_base_max": 120,
        "damage_per_level": 0,
        "equipment": [
            {"name": "Captain Longsword", "item_type": "weapon", "size": "medium", "weight": 2.9, "volume": 1.9, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 35},
            {"name": "Captain Plate", "item_type": "armor", "size": "medium", "weight": 12.0, "volume": 3.6, "armor_class": "heavy", "armor_rating": 36, "block_threshold_bonus": 6},
        ],
        "loot_currency": {"gold": 1, "silver": 12, "copper": 70},
        "loot_items": [],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
    "guard_general": {
        "category": "humanoid",
        "level_min": 55,
        "level_max": 55,
        "hp_base": 1700,
        "hp_per_level": 0,
        "attack_base": 116,
        "attack_per_level": 0,
        "dodge_base": 58,
        "dodge_per_level": 0,
        "block_base": 108,
        "block_per_level": 0,
        "damage_base_min": 155,
        "damage_base_max": 260,
        "damage_per_level": 0,
        "equipment": [
            {"name": "General Warblade", "item_type": "weapon", "size": "medium", "weight": 3.3, "volume": 2.1, "hand_usage": "one_handed", "weapon_family": "sword", "item_level": 55},
            {"name": "General Aegis", "item_type": "shield", "size": "medium", "weight": 5.0, "volume": 2.6, "armor_rating": 20, "block_bonus": 14, "block_threshold_bonus": 9},
            {"name": "General Plate", "item_type": "armor", "size": "large", "weight": 16.0, "volume": 4.2, "armor_class": "heavy", "armor_rating": 54, "block_threshold_bonus": 10},
        ],
        "loot_currency": {"gold": 4, "silver": 25, "copper": 90},
        "loot_items": [{"name": "Officer Seal", "item_type": "quest", "size": "tiny", "weight": 0.1, "volume": 0.1}],
        "allows_surrender": True,
        "allows_spare": True,
        "allows_ceasefire": True,
    },
}


ARCHETYPE_ALIASES = {
    "rat": "rat_small",
    "field_rat": "rat_small",
    "cellar_rat": "cellar_rat",
    "river_rat": "cellar_rat",
    "rabbit": "small_prey",
    "hare": "small_prey",
    "bat_swarm": "bat_swarm",
    "spider_swarm": "spider_swarm_small",
    "small_spider_swarm": "spider_swarm_small",
    "venomous_snake_small": "venom_snake_small",
    "slime": "slime_common",
    "slime_tiny": "slime_tiny",
    "tiny_slime": "slime_tiny",
    "slime_common": "slime_common",
    "acid_slime": "slime_acid",
    "slime_acid": "slime_acid",
    "elder_slime": "slime_elder",
    "slime_elder": "slime_elder",
    "venom_snake_large": "venom_snake_large",
    "wolf_scout": "wolf_scout",
    "wolf_pack_hunter": "wolf_pack_hunter",
    "wolf": "predator_medium",
    "wild_boar": "wild_boar",
    "boar_alpha": "boar_alpha",
    "boar": "brute_beast",
    "bear": "brute_beast",
    "reef_shark_small": "reef_shark_small",
    "shark": "aquatic_predator",
    "crocodile": "aquatic_predator",
    "street_thug_novice": "street_thug_novice",
    "pickpocket": "pickpocket",
    "bandit_cutpurse": "bandit_cutpurse",
    "bandit_raider": "bandit_raider",
    "deserter_soldier": "deserter_soldier",
    "goblin_skirmisher": "goblin_skirmisher",
    "orc_scout": "orc_scout",
    "restless_spirit_minor": "restless_spirit_minor",
    "grave_walker": "grave_walker",
    "bandit": "thug_bandit",
    "thug": "thug_bandit",
    "guard": "guard_standard",
    "city_guard": "guard_standard",
    "captain": "guard_captain",
    "general": "guard_general",
    "civilian": "civilian_weak",
    "worker": "civilian_worker",
}


def _clamp_level(archetype: dict, requested_level) -> int:
    min_level = int(archetype["level_min"])
    max_level = int(archetype["level_max"])
    if requested_level is None:
        return min_level
    level = int(requested_level)
    return max(min_level, min(max_level, level))


def _as_item_payload(item: dict) -> dict:
    payload = deepcopy(item)
    payload.setdefault("description", "")
    payload.setdefault("stackable", False)
    payload.setdefault("quantity", 1)
    payload.setdefault("hand_usage", "none")
    payload.setdefault("item_id", f"loot_{payload.get('name', 'item').lower().replace(' ', '_')}")
    if payload.get("item_type") == "weapon":
        payload.setdefault("combat_profile", {
            "weapon_family": payload.get("weapon_family", "improvised"),
            "item_level": int(payload.get("item_level", 1)),
        })
    if payload.get("item_type") in {"armor", "shield"}:
        payload.setdefault("combat_profile", {
            "armor_rating": float(payload.get("armor_rating", 0)),
            "armor_class": payload.get("armor_class", "medium"),
            "block_threshold_bonus": float(payload.get("block_threshold_bonus", 0)),
            "block_bonus": float(payload.get("block_bonus", 0)),
        })
    payload.pop("weapon_family", None)
    payload.pop("item_level", None)
    payload.pop("armor_class", None)
    payload.pop("armor_rating", None)
    payload.pop("block_bonus", None)
    payload.pop("block_threshold_bonus", None)
    return payload


def build_enemy_from_payload(enemy_payload: dict, index: int) -> dict:
    payload = enemy_payload or {}
    raw_id = str(payload.get("archetype_id") or payload.get("type") or payload.get("kind") or "").strip().lower()
    archetype_id = ARCHETYPE_ALIASES.get(raw_id, raw_id)
    archetype = ENEMY_ARCHETYPES.get(archetype_id, ENEMY_ARCHETYPES["thug_bandit"])
    level = _clamp_level(archetype, payload.get("level"))

    hp_max = max(1, int(round(archetype["hp_base"] + max(0, level - archetype["level_min"]) * archetype["hp_per_level"])))
    attack_score = float(archetype["attack_base"] + max(0, level - archetype["level_min"]) * archetype["attack_per_level"])
    dodge_score = float(archetype["dodge_base"] + max(0, level - archetype["level_min"]) * archetype["dodge_per_level"])
    block_score = float(archetype["block_base"] + max(0, level - archetype["level_min"]) * archetype["block_per_level"])
    damage_min = max(1, int(round(archetype["damage_base_min"] + max(0, level - archetype["level_min"]) * archetype["damage_per_level"])))
    damage_max = max(damage_min, int(round(archetype["damage_base_max"] + max(0, level - archetype["level_min"]) * archetype["damage_per_level"] * 1.1)))

    equipment = deepcopy(archetype.get("equipment", []))
    explicit_equipment = payload.get("equipment")
    if isinstance(explicit_equipment, list) and explicit_equipment:
        equipment = deepcopy(explicit_equipment)

    loot_items = [_as_item_payload(item) for item in (payload.get("loot_items") if isinstance(payload.get("loot_items"), list) else archetype.get("loot_items", []))]
    quest_items = [_as_item_payload(item) for item in (payload.get("quest_items") if isinstance(payload.get("quest_items"), list) else [])]

    return {
        "combat_id": f"enemy_{index}",
        "name": str(payload.get("name", payload.get("display_name", archetype_id.replace('_', ' ').title()))).strip() or f"Enemy {index}",
        "archetype_id": archetype_id,
        "category": archetype.get("category", "humanoid"),
        "level": int(level),
        "hp_current": hp_max,
        "hp_max": hp_max,
        "attack_score": float(payload.get("attack_score", attack_score)),
        "dodge_score": float(payload.get("dodge_score", dodge_score)),
        "block_score": float(payload.get("block_score", block_score)),
        "block_threshold_bonus": float(payload.get("block_threshold_bonus", 0)),
        "damage_min": max(1, int(payload.get("damage_min", damage_min))),
        "damage_max": max(1, int(payload.get("damage_max", damage_max))),
        "initiative": int(payload.get("initiative", 8 + level // 3)),
        "allows_surrender": bool(payload.get("allows_surrender", archetype.get("allows_surrender", False))),
        "surrender_outcome": str(payload.get("surrender_outcome", "captured")).strip().lower() or "captured",
        "allows_spare": bool(payload.get("allows_spare", archetype.get("allows_spare", True))),
        "spare_outcome": str(payload.get("spare_outcome", "released")).strip().lower() or "released",
        "allows_ceasefire": bool(payload.get("allows_ceasefire", archetype.get("allows_ceasefire", False))),
        "ceasefire_outcome": str(payload.get("ceasefire_outcome", "disengaged")).strip().lower() or "disengaged",
        "status": "alive",
        "equipment": equipment,
        "loot_currency": deepcopy(payload.get("loot_currency", archetype.get("loot_currency", {"gold": 0, "silver": 0, "copper": 0}))),
        "loot_items": loot_items,
        "quest_items": quest_items,
        "loot_granted": False,
    }
